# Generated by Django 3.1.7 on 2023-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=50, unique=True)),
                ('url_category', models.SlugField(max_length=100, unique=True)),
                ('description_category', models.TextField(blank=True, max_length=255)),
                ('pic_category', models.ImageField(blank=True, upload_to='pictures/categories')),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
