# Generated by Django 4.2.1 on 2023-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_id_variation'),
        ('cart', '0003_remove_itemcart_user_alter_cart_id_alter_itemcart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='variations',
            field=models.ManyToManyField(blank=True, to='shop.variation'),
        ),
    ]
