# Generated by Django 4.2.1 on 2023-05-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='surname',
        ),
    ]
